# conda env create -f requirements-gpu.yml
name: ctlearn
channels:
    - conda-forge
    - menpo
dependencies:
    - python=3.6.5
    - matplotlib
    - numpy
    - astropy
    - opencv3
    - pillow
    - pip
    # TensorFlow-GPU v1.9.0:
    - pip:
        - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.9.0-cp36-cp36m-linux_x86_64.whl
    - pytables
    - pyyaml
    - scikit-learn
    - scipy
